name: Free Windows 11 RDP
on: workflow_dispatch

jobs:
  launch-windows:
    runs-on: windows-latest
    steps:
      - name: Download and Configure ngrok
        run: |
          Invoke-WebRequest -Uri https://equinox.io -OutFile ngrok.zip
          Expand-Archive .\ngrok.zip -DestinationPath .
          .\ngrok.exe config add-authtoken "${{ secrets.NGROK_AUTH_TOKEN }}"

      - name: Enable Remote Desktop (RDP) Ports
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

      - name: Setup Custom RDP Password
        run: |
          $Password = ConvertTo-SecureString "MySpeedWindows2026!" -AsPlainText -Force
          $User = Get-LocalUser -Name "runneradmin"
          Set-LocalUser -User $User -Password $Password

      - name: Start Safe RDP Tunnel
        run: |
          Start-Process .\ngrok.exe -ArgumentList "tcp 3389"
          Write-Host "RDP Server Started Successfully!"
          Start-Sleep -Seconds 21600 # সেশনটি ৬ ঘণ্টা সচল থাকবে
