name: Free Windows 11 RDP
on: workflow_dispatch

jobs:
  launch-windows:
    runs-on: windows-latest
    steps:
      - name: Install ngrok via Chocolatey
        run: |
          choco install ngrok -y

      - name: Configure ngrok Token
        run: |
          ngrok config add-authtoken "${{ secrets.NGROK_AUTH_TOKEN }}"

      - name: Enable Remote Desktop (RDP) Ports
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Setup Custom RDP Password
        run: |
          # পাওয়ারশেল বাদ দিয়ে অফিশিয়াল উইন্ডোজ কমান্ড দিয়ে পাসওয়ার্ড সেট করা
          net user runneradmin MySpeedWindows2026!

      - name: Start Safe RDP Tunnel
        run: |
          Start-Process ngrok -ArgumentList "tcp 3389"
          Write-Host "RDP Server Started Successfully!"
          Start-Sleep -Seconds 21600 # সেশনটি ৬ ঘণ্টা সচল থাকবে
